/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hqrgtqkjuexijxzsptyq";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxcmd0cWtqdWV4aWp4enNwdHlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcxODkwNzQsImV4cCI6MjA4Mjc2NTA3NH0.vTuLPpAEC9U0edwjUgEhQX9UXr7UUhLUONrvK9XKSwI";
